### ISSUE TITLE
brth

### ISSUE THREAD

**Issue by KadeDev** [fydne/Qurre#1]
you still haven't done anything, you need to use the correct licence. you honestly deserve a DMCA at this point.

**Comment by fydne** [comment]
why? I seem to be using the correct license

**Comment by galaxy119** [comment]
You are required to give the full license, not a snippet from it, see:
https://github.com/galaxy119/EXILED/blob/master/LICENSE.md

**Comment by fydne** [comment]
its a full license
(ctrl c+ctrl v)

**Comment by PintTheDragon** [comment]
Also not 100% about the license stuff, but your link goes to EXILED 2. The correct link is https://github.com/galaxy119/EXILED/tree/1.11-Archived.

**Comment by fydne** [comment]
thx
